config/routes.rb
Rails.application.routes.draw do
  root to: "transactions#new"
  resources :transactions, only: %i[new create show]
  get '/admin', to: 'admin#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  NETWORK_FEE = 0.000006
  EXCHANGE_FEE_PERCENTAGE = 0.03
  MAX_USDT_PER_TRANSACTION = 30

  enum status: { fail: 0, success: 1 }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'admin', on: :show

  def show
    @transactions = Transaction.all
    @success_transactions = @transactions.success
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    build_transaction
  end

  def create
    @transaction_form = TransactionCreateForm.new(create_params)

    if transaction = @transaction_form.call
      redirect_to transaction_path(id: transaction.id)
    else
      render :new
    end
  end

  def show
    @transaction = Transaction.find_by(id: params[:id])
  end

  private

  def create_params
    params.require(:transaction_create_form)
          .permit(:email, :address, :amount_base, :exchange_rate, :terms, :base, :target)
  end

  def build_transaction
    build_params = {
      base: 'UST',
      target: 'BTC',
      exchange_rate: CurrentRateService.new.call
    }

    @transaction_form = TransactionCreateForm.new(build_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
  def present_btc(value)
    return unless value

    sprintf("%.8f", value)
  end

  def present_ust(value)
    return unless value

    sprintf("%.2f", value)
  end

  def present_network_fee
    present_btc(Transaction::NETWORK_FEE)
  end

  def present_amount_base(transaction)
    present_ust(transaction.amount_base)
  end

  %w[amount_target exchange_rate exchange_fee].each do |field|
    define_method("present_#{field}") do |transaction|
      present_btc(transaction.send(field))
    end
  end
end

app/views/admin/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="panel-body panel-height">
      <table class="table table-striped table-responsive table-bordered">
       <thead>
        <h6>Statistics</h6>
        <tr>
          <th>Total Exchange Fee</th>
          <th>Total Transactions</th>
          <th>Total Success Transactions</th>
        </tr>
       </thead>
       <tbody>
          <tr>
            <td><%= @success_transactions.sum(:exchange_fee) %></td>
            <td><%= @transactions.count %></td>
            <td><%= @success_transactions.count %></td>
          </tr>
       </tbody>
      </table>
    </div>

    <div class="panel-body panel-height">
      <table class="table table-striped table-responsive table-bordered">
       <thead>
        <h6>Transactions</h6>
        <tr>
          <th>id</th>
          <th>date/time</th>
          <th>email</th>
          <th>txid</th>
          <th>from</th>
          <th>to</th>
          <th>exchange rate</th>
          <th>exchange fee</th>
          <th>status</th>
        </tr>
       </thead>
       <tbody>
        <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.id %></td>
            <td><%= transaction.created_at.strftime('%Y.%m.%d %H:%M:%S') %></td>
            <td><%= transaction.email %></td>
            <td><%= transaction.txid %></td>
            <td><%= transaction.base %></td>
            <td><%= transaction.target %></td>
            <td><%= transaction.exchange_rate %></td>
            <td><%= transaction.exchange_fee %></td>
            <td><%= transaction.status %></td>
          </tr>
        <% end %>
       </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BtcExchange</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/_error.html.erb
<% unless objet_with_errors.nil? %>
  <% if (errors = objet_with_errors.errors.where(error_of)).any? %>
    <div class="alert alert-danger text-center p-0 m-0">
      <% errors.each do |error| %>
        <p class="small p-0 m-0"><%= error.full_message %></p>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/transactions/_form.html.erb
<div class="card" style="width: 50rem;">
  <div class="card-body container">
    <%= form_for @transaction_form, url: transactions_path, method: :post, data: { turbo: false } do |form| %>

    <div class="row form-group">
      <%= form.label :email, "Email" %>
      <div class="col">
        <%= form.text_field :email, class: "form-control" %>
      </div>
      <%= render partial: 'error', locals: { objet_with_errors: @transaction_form, error_of: :email } %>
    </div>

    <div class="row form-group">
      <%= form.label :amount_base, 'You send' %>
      <div class="col-9 pe-3">
        <%= form.text_field :amount_base, value: present_amount_base(@transaction_form), class: "form-control" %>
      </div>
      <div class="col-3">
        <%= form.text_field :base, readonly: true, class: "form-control" %>
      </div>
      <%= render partial: 'error', locals: { objet_with_errors: @transaction_form, error_of: :amount_base } %>
    </div>

    <div class="row form-group">
      <%= form.label :amount_target, "You get" %>
      <div class="col-9 pe-3">
        <%= form.text_field :amount_target, value: present_amount_target(@transaction_form), class: "form-control" %>
      </div>
      <div class="col-3">
        <%= form.text_field :target, readonly: true, class: "form-control" %>
      </div>
      <%= render partial: 'error', locals: { objet_with_errors: @transaction_form, error_of: :amount_target } %>
    </div>

    <div class="row form-group">
      <%= form.label :address, "Recipient address" %>
      <div class="col">
        <%= form.text_field :address, class: "form-control" %>
      </div>
      <%= render partial: 'error', locals: { objet_with_errors: @transaction_form, error_of: :address } %>
    </div>

    <div class="row form-group">
      <div class="col-6">
        <%= form.label :exchange_fee, "Exchange Fee 3%" %>
        <%= form.text_field :exchange_fee, class: "form-control", value: present_exchange_fee(@transaction_form), readonly: true %>
      </div>
      <div class="col-6">
        <label for="network_fee">Network Fee</label>
        <input type="text" id="network_fee" class="form-control" readonly=true value=<%= present_network_fee %>>
      </div>
    </div>

    <div class="row form-group">
      <div class="col">
        <%= form.label :exchange_rate, "Exchange Rate" %>
        <%= form.text_field :exchange_rate, value: present_exchange_rate(@transaction_form), class: "form-control", readonly: true %>
      </div>
      <%= render partial: 'error', locals: { objet_with_errors: @transaction_form, error_of: :exchange_rate } %>
    </div>

    <div class="row form-group">
      <div class="col">
        <%= form.label :terms, "I agree with Terms of Use", class: "form-check-label" %>
        <%= form.check_box :terms, class: "form-check-input" %>
      </div>
      <%= render partial: 'error', locals: { objet_with_errors: @transaction_form, error_of: :terms } %>
    </div>

    <div class="row form-group">
      <div class="col">
        <%= form.submit "Send", class: "btn btn-primary mt-2" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="container" data-app="transactions-new">
  <div class="row justify-content-center">
    <%= render 'form', transaction: @transaction_form %>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="container" data-app="transactions-new">
  <div class="row justify-content-center">
    <div class="card" style="width: 50rem;">
      <div class="card-header">
        <h5>Checkout</h5>
      </div>
      <div class="card-body container">
        <div class="row">
          <div class="col-6">
            <h6>You Send</h6>
            <p><%= @transaction.amount_base %></p>
          </div>
          <div class="col-6">
            <h6>You Get</h6>
            <p><%= @transaction.amount_target %></p>
          </div>
        </div>

        <div class="row">
          <div class="col-6">
            <h6>Exchange Fee</h6>
            <p><%= @transaction.exchange_fee %></p>
          </div>

          <div class="col-6">
            <h6>Network Fee</h6>
            <p><%= present_btc(Transaction::NETWORK_FEE) %></p>
          </div>
        </div>

        <div class="row">
          <div class="col-6">
            <h6>Recipient Address</h6>
            <p><%= @transaction.address %></p>
          </div>

          <div class="col-6">
            <h6>Exchange Rate</h6>
            <p> 1 <%= @transaction.base %> ~ <%= @transaction.exchange_rate %> <%= @transaction.target %></p>
          </div>
        </div>

        <div class="row justify-content-center">
          <div class="col-auto">
            <%= link_to "New Transaction",
                        new_transaction_path,
                        class: 'btn btn-primary mt-2' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>